import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'lpresswood' at '4/14/17 7:01 AM' with Gradle 3.0
 *
 * @author lpresswood, @date 4/14/17 7:01 AM
 */
class StringFun {

    private static final char OPEN_PAREN = '(', CLOSE_PAREN = ')', COMMA = ',', SPACE = ' ';

    @SuppressWarnings("empty")
    List<String> parseString(String inputString) {

        List<String> parsedString = new ArrayList<>();
        StringBuilder prefix = new StringBuilder();
        String curWord;
        for (int i = 1; i < inputString.length(); ++i) {

            if (inputString.charAt(i) == OPEN_PAREN) {
                prefix.append("-");
            } else if (inputString.charAt(i) == COMMA || inputString.charAt(i) == SPACE) {
                //ignore
            } else if (inputString.charAt(i) == CLOSE_PAREN) {
                if (prefix.length() > 0)
                    prefix = new StringBuilder(prefix.substring(1));
            } else {
                curWord = "";
                while (i < inputString.length()) {
                    if (Character.isAlphabetic(inputString.charAt(i))) {
                        curWord += inputString.charAt(i);
                        ++i;
                    } else {
                        parsedString.add(prefix  + curWord);
                        --i;
                        break;
                    }
                }
            }
        }

        return parsedString;
    }

    List<String> sortParseString(String inputString){
        List<String> rawParsed = parseString(inputString);
        return rawParsed.stream().sorted().collect(Collectors.toList());
    }


    static class ParsedData{
        private String prefix;
        private String data;

        public ParsedData(String prefix, String data) {
            this.prefix = prefix;
            this.data = data;
        }

        @Override
        public String toString() {
            final StringBuffer sb = new StringBuffer(prefix);
            sb.append(data);
            return sb.toString();
        }
    }

}
