import org.junit.Before;
import org.junit.Test;

import java.util.ArrayList;
import java.util.List;

import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'lpresswood' at '4/14/17 7:01 AM' with Gradle 3.0
 *
 * @author lpresswood, @date 4/14/17 7:01 AM
 */
public class StringFunTest {
    String testString = "(id,created,employee(id,firstname,employeeType(id), lastname),location)";

    StringFun parser;

    @Before
    public void init(){
        parser = new StringFun();
    }

    @Test
    public void testParse() {

        ArrayList<String> expected = new ArrayList<>();
        expected.add("id");
        expected.add("created");
        expected.add("employee");
        expected.add("-id");
        expected.add("-firstname");
        expected.add("-employeeType");
        expected.add("--id");
        expected.add("-lastname");
        expected.add("location");

        List<String> results = parser.parseString(testString);
        assertNotNull(results);
        assertTrue(results.size() == 9);
        assertEquals(expected, results);

    }

    @Test
    public void testSortedParse(){
        List<String> results = parser.sortParseString(testString);
        assertNotNull(results);
        assertTrue(results.size() == 9);

    }

}
